FROM microsoft/aspnetcore-build:2.0.3 AS builder
WORKDIR /source

COPY *.csproj .
RUN dotnet restore

# copies the rest of your code
COPY . .
RUN dotnet publish --output /app/ --configuration Release

# Stage 2
FROM microsoft/aspnetcore:2.0.3
WORKDIR /app
COPY --from=builder /app .
ENTRYPOINT ["dotnet", "Wikiled.Dictionary.Web.dll"]

